name: CICD

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build Project
        run: |
          npm install
          npm run build --if-present
      - name: Test Project
        run: npm test
